#ifndef	NQS_VERSION_INCLUDED
#define NQS_VERSION_INCLUDED

#define MAKE_STR_HELPER(x) #x
#define MAKE_STR(x) MAKE_STR_HELPER(x)

#define NQS_VERSION_MAJOR		2
#define NQS_VERSION_MINOR		3
#define NQS_VERSION_PATCH		3
#define NQS_VERSION_BETA		0
#define NQS_VERSION_VERSTRING	MAKE_STR(NQS_VERSION_MAJOR) "." MAKE_STR(NQS_VERSION_MINOR) "." MAKE_STR(NQS_VERSION_PATCH) "." MAKE_STR(NQS_VERSION_BETA)

#endif
